quarkus.devservices.enabled=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=admin123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/cfm-data

quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.http.auth.form.enabled=true

# Optional: Configure the login page, error page, and post-login/logout redirects
quarkus.http.auth.form.login-page=/login
quarkus.http.auth.form.error-page=/unauthorized
quarkus.http.auth.form.landing-page=/dashboard
quarkus.http.auth.form.http-only-cookie=true
quarkus.rest-csrf.require-form-url-encoded=false
# Use the default j_security_check endpoint for form submission
